accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='SignUp'),
]

posts/urls.py
from django.conf.urls import url


from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)',views.UserPosts.as_view(),name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),

]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls'),name='accounts'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Star Social</title>
  <!-- CSS Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- JS Bootstrap -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  <!-- <link rel="stylesheet" href="% static 'simplesocial/static/css/master.css'% "> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mynav" role='navigation' id='navbar'>
    <div class="container">
      <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
      <ul class="navbar-nav justify-content-end">
        {% if user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:create' %}"> <i class="fa fa-sticky-note"></i> Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'groups:all' %}"> <i class="fa fa-users"></i> Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'groups:create' %}"> <i class="fa fa-plus-circle"></i> Create Group</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}"><i class="fa fa-times-circle"></i> Log out</a>
        </li>

        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'groups:all' %}"><i class="fa fa-users"></i> Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}"><i class="fa fa-plug"></i> Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:SignUp' %}"><i class="fa fa-user-plus"></i> Sign Up</a>
        </li>

        {% endif %}
      </ul>

    </div>
  </nav>
  <div class="container">
    {% block content %}

    {% endblock %}
  </div>

  <canvas id="canvas"></canvas>

</body>
<script src="{% static 'simplesocial/js/master.js'%}" type="text/javascript"></script>

</html>

templates/index.html
{%extends "base.html"%}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>
  {% block content %}
  <h1 class="mt-4">Welcome to Star Social!</h1>
  {% endblock %}
</body>

</html>

templates/test.html
{%extends "base.html"%}
{% block content %}
<h1 class="mt-3">You are now logged in</h1>
{% endblock %}

templates/thanks.html
{%extends "base.html"%}
{% block content %}
 <h1 class="mt-3">Thanks for visiting, come back soon!</h1>
{% endblock %}